ci-queue.gemspec
lib/ci/queue/redis.rb
lib/ci/queue/redis/base.rb
lib/ci/queue/redis/retry.rb
lib/ci/queue/redis/worker.rb
lib/minitest/queue.rb
lib/minitest/reporters/failure_formatter.rb
lib/minitest/reporters/redis_reporter.rb
test/fixtures/dummy_test.rb
test/fixtures/test_helper.rb
test/integration/redis_test.rb
test/minittest/reporters/redis_reporter_test.rb
test/support/output_helpers.rb
test/test_helper.rb

Add a RedisReporter for minitest, to be able to centralize the result for the CI run.
@Shopify/pipeline for review please (Note: It's at 99% what was inside Shopify, with added test coverage.)

Add RedisReporter for minitest

---

lib/ci/queue/redis/worker.rb
test/ci/queue/redis_test.rb
test/support/queue_helpers.rb

Since the worker is ready to pop a test right after it requeued a failing one, almost everytime it's the same worker that re-runs it.
It's not terrible, but it would be better if the test was re-ran by another worker, because if the test was failing due to some leaked state, another worker have more chances to make it pass.
Alternatively we could `lpush` the test back, but I'm not a fan since it mean all the requeued tests would be re-ran at the end of the build, so if you configured the queue to requeue tests more than once, it would have detrimental effect on performance.
Also you might wonder: why a static offset? 
Initially I wanted to randomize it based on the number of workers, but then realized we don't have that information ATM, and it seemed like another information to pass to …

Requeue tests with an offset

---

lib/minitest/queue.rb

`msg` doesn't exist here. Was throwing errors for me locally.
@byroot

Fix for missing variable

---

lib/minitest/reporters/order_reporter.rb
test/minitest/reporters/order_reporter_test.rb
test/minitest/reporters/redis_reporter_test.rb
test/support/reporter_test_helper.rb
test/test_helper.rb

This reporter logs the test in a file in the order they were executed. The log can then be used to populate `CI::Queue::File` to replay the tests in the same order.
@Shopify/pipeline for review.

Implement Minitest::Reporters::OrderReporter

---

ci-queue.gemspec
lib/ci/queue/redis/worker.rb
test/fixtures/redis-runner.rb
test/integration/redis_test.rb

If Redis is unreacheable, we assume that either:
- It's just for that single worker, in this case other workers will pick up the slack.
- It's actually down for everyone, the summary step will detect it.
@Shopify/pipeline for review please.

Handle redis being down / unreachable

---

lib/ci/queue/redis/base.rb
lib/ci/queue/redis/worker.rb
test/ci/queue/redis_supervisor_test.rb
test/ci/queue/redis_test.rb

@Shopify/pipeline for review. I wasn't 100% sure when is best to call `register`, but doing so after the tests are pushed means at least the environment is sane.

Register workers on boot, surface on `Redis::Base`

---

lib/minitest/reporters/order_reporter.rb
test/minitest/reporters/order_reporter_test.rb

This allows us to spot which tests was running in case of problems, like timeouts or segfaults.

Write the test to the test order log file before it’s run, rather than after

---

python/Makefile
python/ciqueue/distributed.py
python/tests/shared.py

This fixes the issue we were seeing in starscream where an infrastructure error would occur mid-test, and we'd wait indefinitely for the `test summary` to complete. The problem was that we were exiting the test worker loop before all the tests were completed.
Thanks @casperisfine for explaining how it _should_ work. That really helped me debug this.

fix exiting of testloop before all tests have returned

---

ruby/lib/minitest/reporters/redis_reporter.rb

Since they include the backtrace etc, error reports can be quite big. If for some reason all the test of a build fail (some low level error), it can generate huge amount of error report in redis, and trigger lots of evictions.
This PR allow the host project to customize how the error reports are encoded, allowing to use more efficient encoders then straight Marshal, e.g Marshal + gzip, or messagepack + snappy, etc
cc @solackerman could be worth adding a similar capacity to the pytest version.

Allow to customize error encoder

---

python/ciqueue/_pytest/outcomes.py
python/ciqueue/_pytest/test_queue.py
python/ciqueue/distributed.py
python/ciqueue/pytest.py
python/integrations/pytest/test_flakey.py
python/tests/test_pytest.py

This is what it looks like on the worker agents:
In this example, 3 tests are retried, and marked as skipped.

retry failed tests in python

---

python/ciqueue/_pytest/test_queue.py
python/ciqueue/pytest.py
python/ciqueue/pytest_report.py
python/tests/test_pytest.py

This PR fixes a bunch of little things with the python implementation:
- it adds compression/decompression for the errors being pushed to redis. This is already a feature in the ruby implementation.
- `key_item(item)` now returns pytest's builtin test identifier, instead of the something made up.
- when reporting that a test will be retried, we will now output the message `WILL_RETRY` instead of `RETRYING`.
- when an error occurs while collecting the tests, we no longer push the tests to ci anyways. This fixes https://github.com/Shopify/ci-queue/issues/30 where the summary agent waits indefinitely for the tests to complete.

small fixes

---

python/ciqueue/_pytest/outcomes.py

This PR fixes the following error:
https://buildkite.com/shopify/starscream-production-ci/builds/2118#528b0851-8c5c-4652-b728-31a2d52e8c23
It's possible for dill.pickles(...) to raise an Exception while trying to determine if an object is picklable or not. In all such cases, it's not picklable and should return False.

catch pickles exception

---

ruby/lib/ci/queue.rb
ruby/lib/ci/queue/index.rb
ruby/lib/ci/queue/redis/base.rb
ruby/lib/ci/queue/redis/supervisor.rb
ruby/lib/ci/queue/redis/worker.rb
ruby/lib/ci/queue/static.rb
ruby/test/ci/queue/file_test.rb
ruby/test/ci/queue/redis_supervisor_test.rb
ruby/test/ci/queue/redis_test.rb
ruby/test/ci/queue/static_test.rb
ruby/test/fixtures/redis-runner.rb
ruby/test/minitest/reporters/redis_reporter_test.rb
ruby/test/support/shared_queue_assertions.rb

Fix: https://github.com/Shopify/ci-queue/issues/19
This allows to check if the queue was exhausted without having to boot the entire test environment, which should allow a late worker to exit faster.
This PR also change the queue interface. Queues now receive and return arbitrary objects instead of strings. This will make it easier to implement adapters for test frameworks others than Minitest.

Decouple queue instantiation and population

---

ruby/lib/minitest/reporters/output_helpers.rb
ruby/lib/minitest/reporters/queue_reporter.rb
ruby/test/integration/redis_test.rb

This way we can augment our output for known service providers while still being provider agnostic.

Allow to customize output based on the CI provider

---

ruby/lib/ci/queue/configuration.rb
ruby/lib/minitest/queue/runner.rb
ruby/test/ci/queue/configuration_test.rb

Another setting that can easily be inferred on popular CI providers.
I'll document this later when I improve the `minitest-queue --help` output.

Inffer a good seed from known CI providers

---

ruby/lib/ci/queue.rb
ruby/lib/ci/queue/output_helpers.rb
ruby/lib/ci/queue/redis/base.rb
ruby/lib/ci/queue/redis/supervisor.rb
ruby/lib/ci/queue/redis/worker.rb
ruby/lib/ci/queue/static.rb
ruby/lib/minitest/queue/runner.rb
ruby/lib/minitest/reporters/failure_formatter.rb
ruby/lib/minitest/reporters/queue_reporter.rb
ruby/lib/minitest/reporters/redis_reporter.rb
ruby/test/integration/redis_test.rb
ruby/test/support/output_test_helpers.rb

This adds a `report` subcommand to `minitest-queue` which provides a decent default usage for `Redis::Supervisor` and `RedisReporter`.
e.g.:
```
$ BUILDKITE=1 RUBYLIB=lib/ exe/minitest-queue report --url 'redis://localhost' --build 1 --timeout 1
--- Waiting for workers to complete
+++ Ran 5 tests, 3 assertions, 2 failures, 1 errors, 1 skips, 1 requeues in 0.01s (aggregated)
FAIL ATest#test_bar
Expected false to be truthy.
test/fixtures/dummy_test.rb:9:in `test_bar'
FAIL ATest#test_flaky
Expected false to be truthy.
test/fixtures/dummy_test.rb:17:in `test_flaky'
ERROR BTest#test_bar
TypeError: String can't be coerced into Fixnum
test/fixtures/dummy_test.rb:28:in `+'
test/fixtures/dummy_test.rb:28:in `test_bar'
```

Add report subcommand to minitest-queue

---

ruby/lib/rspec/queue.rb
ruby/test/fixtures/spec/dummy_spec.rb
ruby/test/integration/rspec_redis_test.rb

It's a bit contrived IMO, but turns out the `example_groups` list is not enough, each of them have "descendants" (nested describes), that you have to iterate over as well.
I also realized I forgot to implement test shuffling for RSpec....

Handle RSpec's ExampleGroup descendants (and fix shuffling)

---

ruby/ci-queue.gemspec
ruby/lib/minitest/reporters/redis_reporter.rb
ruby/test/minitest/reporters/redis_reporter_test.rb

We've seen a 78% reduction is memory usage when we enabled this on out application, so might as well provide it automatically in the gem.
However `snappy` and `msgpack` both being native gems, I'd rather not force the dependency. The optimization will be enabled automatically if the project uses those already. Otherwise it will fallback to `Marshal`.

Built-in SnappyPack codec

---

python/ciqueue/distributed.py
python/tests/test_distributed.py

@solackerman PTAL.
I added a test case that at least makes sure that the expected exception is thrown when a wait_for_master times out. There's no easy way, right now, to test that `wait_for_master` eventually does the right thing when the master isn't there the first time but then shows up later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shopify/ci-queue/51)

Fix a bug introduced in Python3 compatibility, where the reporter could not start before its workers.

---

.travis.yml
bin/before-install
bin/test

Context: Minitest 5.11 was released early this year, and broke the monkey patch we use in ci-queue to implement requeues. So in order to support both versions of minitest we'll need to test both on CI.
Because of this I decided to refactor the `travis.yml` a bit to makes testing 2 versions of minitest easier.

Refactor travis test suite

---

.travis.yml
ruby/ci-queue.gemspec
ruby/lib/minitest/queue.rb
ruby/lib/minitest/queue/runner.rb
ruby/lib/minitest/reporters/bisect_reporter.rb
ruby/lib/minitest/reporters/failure_formatter.rb
ruby/lib/minitest/reporters/order_reporter.rb
ruby/lib/minitest/reporters/queue_reporter.rb
ruby/lib/minitest/reporters/redis_reporter.rb
ruby/test/integration/minitest_bisect_test.rb
ruby/test/support/reporter_test_helper.rb

Minitest 5.11 was released a week ago, and changed the internals significantly breaking compatibility with most reporters out there (`minitest-reporters` included).
This PR test and support both 5.11 and previous versions.

Fix Minitest 5.11 compatibility

---

ruby/lib/ci/queue/redis/retry.rb
ruby/lib/ci/queue/redis/supervisor.rb
ruby/lib/ci/queue/redis/worker.rb
ruby/lib/ci/queue/static.rb
ruby/lib/minitest/queue.rb
ruby/lib/minitest/queue/build_status_recorder.rb
ruby/lib/minitest/queue/build_status_reporter.rb
ruby/lib/minitest/queue/error_report.rb
ruby/lib/minitest/queue/failure_formatter.rb
ruby/lib/minitest/queue/local_requeue_reporter.rb
ruby/lib/minitest/queue/runner.rb
ruby/lib/minitest/reporters/redis_reporter.rb
ruby/test/minitest/queue/build_status_recorder.rb
ruby/test/minitest/queue/error_report_test.rb
ruby/test/test_helper.rb

Followup to https://github.com/Shopify/ci-queue/pull/54
While convenient, these methods where coupling queue implementations with Minitest which is kind of messed up. Also that idea of having reporters matching a queue kind of broke down with the bisect command, and is made unnecessary by #54 since queues now expose a common interface to report build progress and status.
So 🔥

Refactor to get rid of #minitest_reporter methods on Queue implementations

---

ruby/lib/rspec/queue.rb
ruby/lib/rspec/queue/build_status_recorder.rb

It can be improved in several ways, but this is kind of the MVP version.
Example use:
```bash
rspec-queue --queue redis://localhost --build 1 --worker 1
rspec-queue --queue redis://localhost --build 1 --report --timeout 180
```

Centralized reporting for RSpec

---

ruby/lib/ci/queue/redis/worker.rb
ruby/lib/rspec/queue.rb
ruby/test/fixtures/spec/dummy_spec.rb
ruby/test/integration/rspec_redis_test.rb

The monkey patch is particularly tricky because RSpec internals don't expect a single `Example` to be ran twice. The `Example` instances are mutated to keep track of of the run result and then stored in various arrays for later printing the summary.
For example if you skip an example, its `execution_result.status` is set to `:pending` and the example instance is stored in `Reporter#pending_examples`. So if you reset the example instance to be able to run it again, it will stay in the `pending_examples` array and cause all sorts of trouble because it's state will be invalid for most reporters.
To work around this, when we requeue an example, we:
- clone it 
- reset the original example instance, and remove it from the reporter
- Mark the clone as skipped, and add it to the reporter.
I …

Implement requeueing for RSpec

---

ruby/lib/minitest/queue/junit_reporter.rb

the `parse_xml_for` method doesn't parse xml, so I renamed it.
I also updated the hashes for kicks.

rename method and 1.9 hashes

---

ruby/railgun.yml

I had to do this manually, which is odd, but dev now works properly again.

Shopify's internal dev tool now requires a railgun.yml in addition to the dev.yml

---

ruby/lib/minitest/queue/junit_reporter.rb
ruby/test/integration/minitest_redis_test.rb

Somehow we messed that element name up when we moved the code in `ci-queue`.
I checked the spec, it's indeed `testsuites` and not `test_suites`: https://github.com/windyroad/JUnit-Schema/blob/49e95a79cc0bfba7961aaf779710a43a4d3f96bd/JUnit.xsd#L18

Fix JUnitReporter to respect the spec

---

ruby/lib/ci/queue/common.rb
ruby/lib/ci/queue/redis/base.rb
ruby/lib/ci/queue/redis/worker.rb
ruby/lib/minitest/queue/runner.rb

If we run tests from multiple namespaces using chained `minitest-queue` commands, e.g.
```
minitest-queue --namespace suite-a run && minitest-queue --namespace suite-b run
```
then it will be more likely that the queue might be consumed at the start of the `minitest-queue` command.  However, right now it would still load the tests and try to populate the queue before detecting that the queue has already been exhausted.
Avoid doing `load_tests` or `populate_queue` in the `run_command` method if the queue has already been exhausted.
There is a test that makes sure an exception isn't raised if redis is down, so I've added a `rescue_connection_errors` method on the queue to abstractly handle these connection exceptions.

Check if queue is exhausted before loading tests

---

ruby/lib/ci/queue/static.rb
ruby/test/support/shared_queue_assertions.rb

When using ci-queue with redis on a retry, the progress was going over the total, which would result in an ProgressBar::InvalidProgressError exception when using the progress with the ruby-progressbar gem.
Increment the progress on acknowledge so that it isn't also incremented when the test is requeued.
The added test assertion for the progress at the end of the test_requeue test will fail without the included fix.

Fix double counting of requeued tests in redis retry progress

---

shipit.rubygems.yml

By default shipit would look at the top-level of the repository to try to discover how to deploy the project, but the ci-queue repo has separate the ruby gems code into a `ruby` subdirectory.
Add a shipit.yml file that uses [machine.directory](https://github.com/shopify/shipit-engine#directory) to try to deploy from the ruby subdirectory.

Use shipit to release to rubygems

---

ruby/README.md
ruby/lib/ci/queue/configuration.rb
ruby/lib/minitest/queue/runner.rb
ruby/test/ci/queue/configuration_test.rb

Details on env vars are found at:
- https://devcenter.heroku.com/articles/heroku-ci#environment-variables-env-key
- https://devcenter.heroku.com/articles/heroku-ci-parallel-test-runs#parallelizing-your-tests
Splitting up #81 into two different PRs for separate discussion.

Add support for default Heroku CI ENV vars

---

ruby/lib/ci/queue/redis/build_record.rb
ruby/lib/ci/queue/redis/worker.rb
ruby/lib/minitest/queue/runner.rb
ruby/test/ci/queue/redis_test.rb
ruby/test/fixtures/test/passing_test.rb
ruby/test/integration/minitest_redis_test.rb
ruby/test/integration/rspec_redis_test.rb

The worker would simply run the exact same list of tests it ran before failing / crashing
The worker only run the failed test it ran previously. 
If no test failed, then it simply goes back to poll the general queue.
If the general queue is exhausted as well, it early exit.
The previous behavior was implemented as is for consistency reasons, if a test was impacted by a leak we wanted the test order to be the same so that it's replicable.
But really retries happen for two reasons:
- The developer manually retry the job because it failed due to a flaky or leaky test. They actually want the leak not to happen again, so we might as well only retry failures so that it's both faster and less likely to be impacted by the leak.
- The job was retried automatically because we detected an …

Only run failed tests on retry

---

ruby/lib/ci/queue/build_record.rb
ruby/lib/ci/queue/redis/build_record.rb
ruby/lib/minitest/queue/build_status_reporter.rb
ruby/lib/minitest/queue/runner.rb
ruby/test/fixtures/test/flaky_test.rb
ruby/test/integration/minitest_redis_test.rb

In some circumstances, after retrying failed workers a build could end up with the report step complaining about errors, but no error reports not failed workers.
What would happen is that a worker would have failed, but it's failing test would have been retried by another worker. So all test ultimately pass.
However when retrying the first worker, it sees the queue is all worked off and simply bail out with a success.
The problem is that the report job was looking at `failures` and `errors` stats, which would have been left pristine by the retried worker.
The solution here is to look at the `error-reports` hash instead, which has the benefit of being updated in an idempotent way, so is a much better source of truth.
Additionally, workers reset their minitest stats on retry, this will …

Reset minitest stats on retry

---

ruby/lib/minitest/queue/order_reporter.rb

Small change so we can always trust that, while running, the value in the logs is up to date.

Flush `OrderReporter` before running test

---

ruby/lib/ci/queue/common.rb
ruby/lib/ci/queue/redis/worker.rb
ruby/lib/minitest/queue/runner.rb
ruby/lib/rspec/queue.rb
ruby/test/integration/minitest_redis_test.rb
ruby/test/integration/rspec_redis_test.rb

The `retry` subcommand (or `--retry` flag for rspec) makes it hard to integrate on CI, and we realized many of our pipeline didn't integrate that part.
This caused and imperfect behavior that surprises people.
Since not all CI systems expose jobs retry as an env var, I chose to inspect Redis to detect wether we are retrying or not.

Deprecate the retry subcommand and make the behavior automatic

---

ruby/README.md
ruby/lib/ci/queue/configuration.rb
ruby/test/ci/queue/configuration_test.rb

Shopify, thank you for publishing the gem!
I'd like to contribute support for Semaphore 2 with the following defaults:
- Build ID - taken from [`SEMAPHORE_PIPELINE_ID`](https://docs.semaphoreci.com/article/12-environment-variables#semaphore_pipeline_id) (but see my note below)
- Worker ID - taken from [`SEMAPHORE_JOB_ID`](https://docs.semaphoreci.com/article/12-environment-variables#semaphore_job_id)
- Seed - based on [`SEMAPHORE_GIT_SHA`](https://docs.semaphoreci.com/article/12-environment-variables#semaphore_git_sha)
Regarding build ID, I wasn't sure whether to chose `SEMAPHORE_PIPELINE_ID` or [`SEMAPHORE_WORKFLOW_ID`](https://docs.semaphoreci.com/article/12-environment-variables#semaphore_workflow_id). According to [the documentation](https://docs.semaphoreci.com/article/62-concepts), …

Add support for Semaphore 2

---

python/setup.py
ruby/lib/rspec/queue.rb
ruby/test/fixtures/spec/dummy_spec.rb
ruby/test/integration/rspec_redis_test.rb

I bumped `ci-queue` to 0.15.0 for spy, but because it uses rspec I found that the `reset_counters` wasn't in the rspec queue.
EDIT: And is not needed.
I kinda reverse engineered this a bit, but tried to keep it inline with the minitest queue. 
~I'm not sure how to test it either :( I'm not a huge rspec person~ Added test
https://buildkite.com/shopify/spy/builds/10719#39e0272c-08d9-43e9-a75a-afdee9935c23/312-318
Also fixed Python tests

Remove reset_counters method for rspec

---

ruby/.gitignore
ruby/lib/rspec/queue.rb
ruby/lib/rspec/queue/order_recorder.rb
ruby/test/integration/rspec_redis_test.rb

Fix: https://github.com/Shopify/ci-queue/issues/98
Log test order in a file with the RSpec implementation to be able to replay the sequence with `rspec-queue --queue path/to/test_order.log`.
@schneems

Implement test_order logging for RSpec implementation

---

ruby/dev.yml
ruby/lib/rspec/queue.rb

Some jobs are exiting with status `1` even though all the examples they ran succeeded, and the report job succeed.
I suspect it's the `return if RSpec.world.wants_to_quit` which is causing this by returning `nil` from `SingleExample#run`.

rspec-queue: prevent early exit from exiting with a failure status

---

ruby/lib/ci/queue.rb
ruby/lib/ci/queue/configuration.rb
ruby/lib/ci/queue/grind.rb
ruby/lib/ci/queue/redis.rb
ruby/lib/ci/queue/redis/grind.rb
ruby/lib/ci/queue/redis/grind_record.rb
ruby/lib/ci/queue/redis/grind_supervisor.rb
ruby/lib/minitest/queue.rb
ruby/lib/minitest/queue/grind_recorder.rb
ruby/lib/minitest/queue/grind_reporter.rb
ruby/lib/minitest/queue/runner.rb
ruby/test/fixtures/grind_list.txt
ruby/test/fixtures/grind_list_success.txt
ruby/test/fixtures/grind_multiples_list.txt
ruby/test/integration/grind_redis_test.rb
ruby/test/integration/minitest_redis_test.rb
ruby/test/support/output_test_helpers.rb

This is a draft for a grind command, which enables us to check if a test is flaky by running it over and over again. In the current version of ci-queue we are able to run a test multiple times, but we aren't able to summarize it. We require a summary step as it gives us a way to communicate the grinding results in a more understandable way. 
When we try to use the report functionality the previous test runs get overridden by newer ones, which causes the reporting to be wrong. We isolated the problem down to tests not being uniquely identifiable. We solve it by adding a sequential id at the end of every test name.
This solution works, but the changes made to `id` are pretty invasive and will lead to confusion. Do you think there is a better way to solving this problem?
here is an example …

Grind command

---

ruby/lib/ci/queue/configuration.rb

We aren't using the the max_duration flag setter in the configuration initializer. This prevents it to be added to the circuit breakers.
ref #102

fix max duration setter

---

.travis.yml
python/Makefile
python/setup.cfg

To validate that we can run Python 3.7 and 3.8 on ciqueue let's add them to the tox runner!

Add py37 and py38 to `tox`

---

ruby/lib/minitest/queue/runner.rb
ruby/lib/rspec/queue.rb

The newer version of ruby has `<<~` heredoc that does the same thing as the `split_heredoc` method. The PR removes `split_heredoc` and use `<<~` instead.

replace split_heredoc with <<~

---

ruby/lib/ci/queue/redis.rb
ruby/lib/ci/queue/redis/test_time_record.rb
ruby/test/ci/queue/redis/test_time_record_test.rb

Adding the class to store the run time of individual test during a grind in Redis.
Related https://github.com/Shopify/test-infra/issues/36
You can see the entire change at https://github.com/Shopify/ci-queue/pull/112/files

Add TestTimeRecord

---

ruby/lib/minitest/queue.rb
ruby/lib/minitest/queue/test_time_recorder.rb
ruby/test/minitest/queue/test_time_recorder_test.rb

Adding the class to store the run time of individual test during a grind to a build being passed in.
Related https://github.com/Shopify/test-infra/issues/36
You can see the entire change at https://github.com/Shopify/ci-queue/pull/112/files

Add TestTimeRecorder

---

ruby/lib/ci/queue/configuration.rb
ruby/lib/minitest/queue.rb
ruby/lib/minitest/queue/runner.rb
ruby/lib/minitest/queue/test_time_reporter.rb
ruby/test/integration/grind_redis_test.rb
ruby/test/minitest/queue/test_time_reporter_test.rb

Add `--max-test-duration` and `--max-test-duration-percentile` to grind.
Related https://github.com/Shopify/test-infra/issues/36
You can see the entire change at https://github.com/Shopify/ci-queue/pull/112/files

add --max-test-duration feature

---

ruby/.gitignore
ruby/lib/minitest/queue.rb
ruby/lib/minitest/queue/runner.rb
ruby/lib/minitest/queue/test_data.rb
ruby/lib/minitest/queue/test_data_reporter.rb
ruby/test/integration/minitest_redis_test.rb

This PR adds the ability to output data on test results, which is we use for data analysis.
Doing this through json instead of the junit xml gives us an easier time using it and also more flexibility.
ref https://github.com/Shopify/test-infra/issues/100

save test metrics

---

ruby/test/integration/minitest_redis_test.rb

The master branch's CI is not passing because the latest Minitest throws its exception in a different format.
Build: https://travis-ci.org/Shopify/ci-queue/builds/646084447
The PR fixes the problem by checking whether part of the string matches instead of the entire output.

Fix test_redis_reporter because newest version of Minitest

---

ruby/lib/ci/queue/configuration.rb
ruby/lib/ci/queue/version.rb
ruby/lib/minitest/queue/runner.rb
ruby/test/integration/grind_redis_test.rb

Related: https://github.com/Shopify/test-infra/issues/183

Add option to disable TestTimeReporter

---

ruby/dev.yml

This fixes the `dev up` on my machine.

Bump dev.yml to ruby 2.6.5

---

ruby/lib/ci/queue/redis/base.rb
ruby/lib/ci/queue/version.rb

- Increase default wait_for_master timeout from 10s to 30s.
- Bump patch version
This could mitigate issues with timeouts in worker polling: https://github.com/Shopify/ci-queue/blob/c6e7640c6b54bd6ccebdeedfe3c371fe86959238/ruby/lib/ci/queue/redis/worker.rb#L47
We can implement exponential backoff at a later time when needed.

Increase wait_for_master timeout to 30s

---

ruby/lib/minitest/queue/failure_formatter.rb
ruby/test/integration/minitest_redis_test.rb

In order for us to ignore certain types of intermittent test failures from being removed from the codebase we have to know what the error class is. This PR adds the error class to the failure file.
ref https://github.com/Shopify/test-infra/issues/225

add error class to failure file

---

.github/workflows/tests.yml
ruby/lib/ci/queue/circuit_breaker.rb
ruby/lib/ci/queue/configuration.rb
ruby/lib/ci/queue/redis/base.rb
ruby/lib/ci/queue/redis/build_record.rb
ruby/lib/ci/queue/redis/supervisor.rb
ruby/lib/ci/queue/redis/worker.rb
ruby/lib/ci/queue/static.rb
ruby/lib/minitest/queue.rb
ruby/lib/minitest/queue/runner.rb
ruby/test/integration/minitest_redis_test.rb

This PR adds a feature to CI-Queue that allows us to short circuit the test workers and summary step. If a build encounters many test failures, then the probability is hight that most of those tests originate from a similar failure source. Short-circuiting test runs in case we have many test failures that allow us to give developers faster feedback and reduce the load on our CI system.
integration build: https://buildkite.com/shopify/shopify-selective-tests/builds/139838

add max test failures feature

---

.github/workflows/tests.yml
ruby/ci-queue.gemspec
ruby/lib/ci/queue/configuration.rb
ruby/lib/ci/queue/output_helpers.rb
ruby/lib/ci/queue/redis/worker.rb
ruby/lib/minitest/queue.rb
ruby/lib/minitest/queue/statsd.rb
ruby/test/ci/queue/redis_test.rb
ruby/test/support/reporter_test_helper.rb

As the title says.
Also since I upgraded rake, it now run tests with extra verbosity by default which led to more warning fixes, such as initialized instance variables etc.

Test and fix deprecation on Ruby 2.7

---

ruby/ci-queue.gemspec
ruby/lib/ci/queue/output_helpers.rb
ruby/lib/minitest/queue/failure_formatter.rb

Since it's the last thing throwing warnings, I figured we should reconsider it. 
For most people these warnings don't matter, but if you are trying to run your test suite with ruby on verbose mode, it's annoying to have warnings coming out of your test runner...
We're only using a terribly small portion of it, it can easily be replaced by a dozen lines of very simple code. I think we can 🔥 it.

Get rid of the dependency on the ansi gem

---

ruby/lib/ci/queue.rb
ruby/lib/minitest/queue.rb
ruby/lib/rspec/queue.rb
ruby/test/fixtures/test/custom_requeue_test.rb
ruby/test/integration/minitest_redis_test.rb

For context I'm using https://github.com/Shopify/deprecation_toolkit to fix Ruby 2.7 keyword argument warnings. The problem is that Ruby only fire these warnings once, so they have a significant false nagative change if they are retried.
But even beyond this, I think it's an useful API, we could probably have other uses for it.
Thoughts?

Add CI::Queue.requeueable to define wether a failure should be requeued

---

ruby/lib/minitest/queue/junit_reporter.rb
ruby/test/integration/minitest_redis_test.rb
ruby/test/minitest/reporters/junit_reporter_test.rb
ruby/test/support/output_test_helpers.rb
ruby/test/support/reporter_test_helper.rb

- Use REXML rather than Builder. Slightly more verbose, but doesn’t turn escape codes into garbage. Also means that we can potentially get rid of a dependency that is no longer maintained.
- Wrap output in CDATA sections so we don’t have to format it according to XML’s rules. We will have to adjust our JUnitXML parser accordingly, because it's currently not handling CDATA sections.
- Add unit tests.

Rewrite JunitReporter.

---

ruby/lib/minitest/queue/junit_reporter.rb
ruby/test/integration/minitest_redis_test.rb
ruby/test/minitest/reporters/junit_reporter_test.rb
ruby/test/support/output_test_helpers.rb

Turns out that XML 1.0 does not (officially) support control characters, like `\e`. The JUnit XML files we generate often include escape characters because we use ANSI color codes in our assertion messages. 
XML 1.1 adds support for these characters. Our parsers are fine with using `\e`, and can use both versions, so this is PR is to make things "technically correct".
At the same time, I've also updated the generator to use double quotes, which I find more pleasant to look at.

Generate XML 1.1 JUnit documents so we can use control characters.

---

ruby/ci-queue.gemspec
ruby/lib/minitest/queue.rb
ruby/lib/minitest/queue/failure_formatter.rb
ruby/test/minitest/queue/test_time_recorder_test.rb
ruby/test/minitest/queue/test_time_reporter_test.rb
ruby/test/support/reporter_test_helper.rb

By bumping the required minitest version to 5.14, we can get rid of a bunch of old cruft:
- We can assume `Minitest::Result` exists.
- It's spelled `Minitest`, not `MiniTest`
~Depends on #140.~

Clean up some old backwards compatibility code that we can get rid off

---

ruby/lib/minitest/queue.rb
ruby/lib/minitest/queue/junit_reporter.rb
ruby/test/integration/minitest_redis_test.rb
ruby/test/minitest/queue/run_command_formatter_test.rb
ruby/test/minitest/reporters/junit_reporter_test.rb
ruby/test/support/reporter_test_helper.rb

When generating JUnitXML, include a `run-command` attribute in every `<testcase>` tag. Readers of the file can use this to tell users how they can re-run tests to diagnose issues.
Because test runners differ between environments, we allow people to register a `run_command_formatter` that returns the run command. We ship it with a basic one that runs tests using `bundle exec ruby -Ilib:test<testfile> -n `<testname>`, and a different formatter for when the Rails test runner is found.

 JUnitXML reporter: add run-command property to test case tags

---

ruby/lib/minitest/queue.rb

My first attempt at detecting whether we can use the Rails test runner was broken. Here is an improved version that I have actually tested locally.

Detect when we can use the rails test runner properly

---

ruby/lib/minitest/queue/junit_reporter.rb
ruby/test/minitest/reporters/junit_reporter_test.rb
ruby/test/support/reporter_test_helper.rb

Fixes #146.
We were too eagerly removing the project root from paths we encounter in assertion messages. Specifically, because our application root is `/app/` on CI, we swould be stripping out path from with paths as well (e.g. `/app/components/app/test/blah.rb` would have the second `/app` stripped).
This fix uses a regular expression to make sure we only remove the project root it from the beginning of stacktrace lines, where they are always at the same place on the line.

Properly remove project root from paths

---

ruby/lib/minitest/queue/error_report.rb
ruby/lib/minitest/queue/failure_formatter.rb
ruby/test/integration/minitest_redis_test.rb

The failure file didn't have data on a test suite, so I'm adding it here.
Fixes once deployed in core: https://github.com/Shopify/test-oversight-service/issues/51

add test suite to failure  file

---

ruby/README.md

This PR adds a message when the rspec test runner is invoked that it is deprecated.
reference https://github.com/Shopify/test-infra/issues/350

add deprecation message to rspec command

---

ruby/ci-queue.gemspec
ruby/lib/ci/queue/redis/worker.rb

Redis 4.2 is somewhat deprecating `exists` for `exists?`. 
So we should use that one in priority if it's available.

Support redis >= 4.2

---

ruby/lib/ci/queue/configuration.rb
ruby/lib/ci/queue/redis/supervisor.rb
ruby/lib/ci/queue/version.rb
ruby/lib/minitest/queue/runner.rb
ruby/test/ci/queue/configuration_test.rb

At the moment the `--timeout` argument has more than one meaning. This PR adds a timeout specific to the initialization of the queue.
The new argument is backward compatible, not requiring a major version update.

Queue init timeout

---

ruby/lib/ci/queue/version.rb
ruby/lib/minitest/queue/junit_reporter.rb
ruby/test/minitest/reporters/junit_reporter_test.rb

This adds some rescue to gracefully handle invalid JUnit XML files.
AFAIK we only use the JUnit files for annotation so we can safely just ignore an invalid character.
We already do a [similar thing in shopify-build](https://github.com/Shopify/shopify-build/blob/4b6765680d064b14dc23c48c2f6ccd49d9885365/lib/shopify_build/artifact_export_directory.rb#L107).
https://buildkite.com/shopify/shopify-selective-tests/builds/303594#0717c9a3-c2d8-4031-92b6-34c014a40320/153-154

Gracefully handle invalid JUnit XML files

---

ruby/lib/ci/queue/version.rb

`0.20.7` was already released so bumping to `0.20.8`.

Bump version for Ruby gem to 0.20.8

---

ruby/lib/ci/queue/version.rb
ruby/lib/minitest/queue.rb
ruby/lib/minitest/queue/test_data.rb
ruby/test/fixtures/test/time_test.rb
ruby/test/integration/minitest_redis_test.rb

Store timestamps related to when a test begun running and when it finished.
We currently have access to the overall time the test took, but not at what point in time the test was run.

Add time details about test runs

---

.github/workflows/tests.yml

https://github.com/actions/setup-ruby has been deprecated and should be replaced with https://github.com/ruby/setup-ruby

update ruby action

---

ruby/lib/minitest/queue/runner.rb

Avoid failing later down the stack with weird Redis errors.
cc @catlee

Exit early if worker or build id is missing

---

ruby/lib/ci/queue/common.rb
ruby/lib/ci/queue/redis/worker.rb
ruby/lib/ci/queue/static.rb
ruby/lib/minitest/queue/runner.rb

Avoid asking for `worker` and `build` while running a leakbot reproducing command in Spin.
Resolves: Shopify/shopify#421914

Fix leakbot command instruction in Spin

---

ruby/test/support/output_test_helpers.rb

Rspec's report will not display the fraction is it's close enough to zero:
```
irb(main):011:0> RSpec::Core::Formatters::Helpers::format_seconds(3.01)
=> "3.01"
irb(main):012:0> RSpec::Core::Formatters::Helpers::format_seconds(3.001)
=> "3"
```
https://github.com/rspec/rspec-core/blob/main/lib/rspec/core/formatters/helpers.rb#L60-L65
I saw a test flake like this:
```
Integration::RSpecRedisTest
test_redis_runner_retry                                         PASS (32.70s)
test_retry_report                                               FAIL (48.07s)
--- expected
+++ actual
@@ -3,7 +3,7 @@
Randomized with seed 123
.
-Finished in X.XXXXX seconds (files took X.XXXXX seconds to load)
+Finished in X.XXXXX seconds (files took 3 seconds to load)
1 example, 0 failures
Randomized with seed 123 …
```

Make seconds fraction optional when normalizing test output

---

ruby/Rakefile
ruby/dev.yml

The whole suite can take a while, it's nice to be able to run specific files when you're debugging something.
Test all: `dev test`
Test specific files: `dev test test/minitest/reporters/*`

Allow specifying files to test with 'dev test'

---

ruby/lib/ci/queue/configuration.rb
ruby/lib/ci/queue/redis/build_record.rb
ruby/lib/minitest/queue/build_status_reporter.rb
ruby/lib/minitest/queue/runner.rb
ruby/test/integration/minitest_redis_test.rb

Export list of flaky tests.
Re-queued jobs are not marked as failed. So, to determine the flakiness I am looking into the re-queue count for the test or check if it failed earlier and passed on job retry.

Export flaky tests

---

ruby/lib/minitest/queue/runner.rb
ruby/test/integration/minitest_redis_test.rb

By default ci-queue overwrites the reporters array.
Minitest's verbose option is only utilized by it's own default reporter and the default reporter that minitest-reporters replaces it with, so the simplest thing to do is to simply include one of those.
The included `LocalRequeueReporter` also displays a summary line, so in this case you get 2 summary lines
However the `DefaultReporter` has a significant amount of logic in it
and the `LocalRequeueReporter` has other functionality
so choosing one over the other doesn't seem right,
nor does it feel worthwhile to recreate the logic.
We could change the LocalRequeueReporter to inherit from DefaultReporter (instead of BaseReporter) and pass our verbose option to that.
We could then remove this code, since the default reporter includes it …

Accept -v/--verbose option and include the usual reporter

---

ruby/test/integration/grind_redis_test.rb

This adds some additional checks and messages to help identify why the test is failing and what might help.
When I first ran the suite with TruffleRuby I was seeing
```
This worker is exiting early because it reached its timeout of 1 seconds
test_grind_max_time                                            ERROR (8.89s)
Minitest::UnexpectedError:         NoMethodError: undefined method `scan' for nil:NilClass
/home/spin/src/github.com/Shopify/ci-queue/ruby/test/integration/grind_redis_test.rb:131:in `test_grind_max_time'
```
This PR:
- captures that STDERR line
- asserts that it is present (to ensure that the subprocess exited for the timeout as expected)
- protects against nil error with a few more assertions
- adds a message about what might be happening and what might help
- measures the …

Make it easier to identify why the grind test might be failing and increase timeout for truffleruby

---

ruby/Gemfile

activesupport 5.x requires tzinfo 1.x which requires thread_safe which has been deprecated in favor of concurrent-ruby.
7 is the latest but it requires ruby 2.7 and we are using 2.6.
I started looking into this when I noticed this output when testing on truffleruby:
> $ bundle exec rake
> ThreadSafe: unsupported Ruby engine, using a fully synchronized ThreadSafe::Cache implementation
concurrent-ruby specifically supports truffleruby.

Upgrade activesupport to next major release (5 -> 6)

---

ruby/Gemfile

Followup: https://github.com/Shopify/ci-queue/pull/223
It's only used in test for the time helpers (e.g. like TimeCop)
There is no point locking to a specific version.

Unlock Active Support

---

ruby/lib/ci/queue/static.rb
ruby/test/ci/queue/file_test.rb
ruby/test/fixtures/test_order.log
ruby/test/support/shared_queue_assertions.rb

The `Minitest::Queue::Runner` [traps signals](https://github.com/Shopify/ci-queue/blob/f6159e0c79471d999aa31d40637e7a81f1654731/ruby/lib/minitest/queue/runner.rb#L82-L83) and sends `shutdown!` to the queue. However, `shutdown!` doesn't exist doesn't exist on `Static` and `File` type queues, resulting in a printed exception, and a runaway test runner. This PR adds `shutdown!` to those queues.
It also fixes a test in the `File` type that wasn't run by virtue of being `private`.

Add shutdown to Static and File queues, and fix some tests

---

.github/workflows/tests.yml
.spin/packages.yml
dev.yml
ruby/test/integration/grind_redis_test.rb
ruby/test/integration/minitest_redis_test.rb

- Install libsnappy-dev as the gem will use the system lib if present.  When not present it installs a vendored one which breaks on truffleruby
- Increase time for subprocess startup by 10s for TruffleRuby
- Add trufflerubyto CI

Run ruby test suite against truffleruby in CI

---

ruby/lib/minitest/queue/runner.rb

We want to instrument how often this happens so adding a different exit code for it.

Exit with status 40 when no master elected

---

ruby/lib/minitest/queue/failure_formatter.rb

Relates to https://github.com/Shopify/test-infra/issues/2213
When we run `minitest-queue report`, a test error (not failure) is dumped as `Minitest::UnexpectedError`. As we're working on improving the merge queue build stability, we want to group test errors by their specific error classes and `Minitest::UnexpectedError` doesn't help with that. This PR changes the error class output to be more specific (follow what we have in [TestDataReporter](https://github.com/Shopify/ci-queue/blob/master/ruby/lib/minitest/queue/test_data.rb#L80)).
🎩 https://buildkite.com/shopify/shopify-selective-tests/builds/1257983#018af5d7-9384-4fa4-a653-5e81b3f7225d/9110-9113
Check out the monorail_test_failures_event.json artifact

Update error_class value in FailureFormatter

---

ruby/lib/ci/queue/redis/build_record.rb
ruby/lib/minitest/queue/build_status_recorder.rb
ruby/test/integration/minitest_redis_test.rb
ruby/test/minitest/queue/build_status_recorder_test.rb

When test fails and are requeued it is treated as skipped for which the `record_success` method is executed and hence these tests are added to the flaky list which is not desired. This PR fixes it by skipping recording of flaky tests for skipped tests.
Tophat: The failing test [in this build](https://buildkite.com/shopify/shopify-selective-tests/builds/1267574#018b2099-ffb2-4afc-85e1-5b781265383a) is no more in the flaky test list.

Fix flaky test record for skipped test

---

ruby/lib/ci/queue/redis.rb
ruby/lib/ci/queue/redis/base.rb

Booting a CI worker is costly, so in case of a Redis blip, it makes sense to retry for a while before giving up.

Ruby/Redis: retry connection errors more agressively

---

.github/workflows/tests.yml
ruby/dev.yml
ruby/lib/ci/queue/configuration.rb
ruby/lib/ci/queue/redis/build_record.rb
ruby/lib/minitest/queue/build_status_reporter.rb
ruby/lib/minitest/queue/runner.rb
ruby/test/integration/minitest_redis_test.rb

We sometimes have builds which abort early and it's not clear why. With this PR we will print out the build stats and flaky tests to debug this further.

Report early exits

---

ruby/lib/minitest/queue/runner.rb

Follow-up on https://github.com/Shopify/ci-queue/pull/272. We're going clean the test order file given to bisect from the client side instead. Specifically from the file which loads all the tests. We're going to introspect the currently existing tests based on what's available in `Minitest::Test.runnables`. To make sure that ci-queue reads the cleaned test order file, we need to initialize the bisect queue after it runs `load_tests`.

Initialize bisect queue after loading tests

---

ruby/lib/minitest/queue/runner.rb

We were incorrectly reaching this code block when a test order file has two tests. This PR fixes the condition for detecting when there is nothing to bisect.

Fix condition for empty bisect

---

ruby/lib/ci/queue/bisect.rb
ruby/lib/minitest/queue/runner.rb
ruby/test/integration/minitest_bisect_test.rb

Since we started periodically reproducing state leaks, I saw some cases where the failing test does not exist anymore. In such cases, the bisect command thinks that the failing test independently fails because the `run_tests_in_fork(queue.failing_test)` returns false - 
```
--- Testing the failing test in isolation
/tmp/bundle/ruby/3.4.0+0/gems/ci-queue-0.52.0/lib/ci/queue/static.rb:91:in 'Hash#fetch': key not found: "Sales::ApiOrderToOrderServiceTest#test_an_order_... (KeyError)
--
  | Did you mean?  "Sales::OrderEditing::LineItemBuilderTest#test_some_other_test"
  | from /tmp/bundle/ruby/3.4.0+0/gems/ci-queue-0.52.0/lib/ci/queue/static.rb:91:in 'CI::Queue::Static#poll'
  | from /tmp/bundle/ruby/3.4.0+0/gems/ci-queue-0.52.0/lib/minitest/queue.rb:229:in 'Minitest::Queue#run_from_queue'
  …
```

Gracefully handle non-existing failing test given to bisect

---

.github/dependabot.yml

Part of ongoing work to standardize our dependabot config.
Move to weekly updates monday at 2pm utc. Group dependencies.

Standardize dependabot

---

ruby/lib/ci/queue/build_record.rb
ruby/lib/ci/queue/redis/build_record.rb
ruby/lib/ci/queue/redis/worker.rb
ruby/lib/minitest/queue.rb
ruby/lib/minitest/queue/build_status_reporter.rb
ruby/lib/minitest/queue/runner.rb
ruby/test/integration/minitest_redis_test.rb

Report worker crashes to summary command.

Report worker crashes to summary command

---

ruby/lib/ci/queue/redis/base.rb
ruby/lib/ci/queue/redis/supervisor.rb
ruby/lib/ci/queue/redis/worker.rb
ruby/lib/minitest/queue/runner.rb
ruby/test/ci/queue/redis_supervisor_test.rb
ruby/test/ci/queue/redis_test.rb
ruby/test/integration/minitest_redis_test.rb
ruby/test/integration/rspec_redis_test.rb
ruby/test/support/shared_queue_assertions.rb

We sometimes have builds timing out pushing tests to the queue but it's hard to debug because I don't know which of the workers is the leader. Adding some log output about leader election and pushing tests to the queue.

Add logs around leader election

---

ruby/Gemfile.lock
ruby/ci-queue.gemspec

Otherwise it output a warning on Ruby 3.4

Declare missing logger dependency

---

ruby/lib/minitest/queue/runner.rb

Otherwise the worker may exit early with
`0 tests left and 0 workers running.`
 

Load tests if queue is not initialized

---

ruby/lib/ci/queue/static.rb

Manual retries will fail since https://github.com/Shopify/ci-queue/pull/296 as the methods doesn't exist on the static queue.

Fix retry queue

---

ruby/lib/ci/queue.rb
ruby/lib/ci/queue/redis.rb
ruby/lib/minitest/queue.rb

In case we use a static queue the errors are not loaded properly.
https://github.com/Shopify/ci-queue/blob/d23f35d1332079183ed337c1caffe436965632fd/ruby/lib/ci/queue.rb#L52-L59
Related to https://github.com/Shopify/ci-queue/pull/298

Fix rescue

---

shipit.rubygems.yml

This prevents continuous deployment to Rubygems

Hide Python on shipit

---

ruby/lib/minitest/queue/junit_reporter.rb
ruby/test/integration/minitest_redis_test.rb
ruby/test/minitest/reporters/junit_reporter_test.rb

Add optional attributes message and stacktrace to skipped children in JunitXML

Add optional attributes message and stacktrace to skipped children in JunitXML

---

ruby/lib/minitest/queue.rb

Fix `undefined local variable or method 'error' for module Minitest` 
The error was raised for `CI::Queue::Error` error as the error object wasn't passed to the rescue block.

Pass error object to CI::Queue::Error rescue block

---

ruby/lib/ci/queue/redis/supervisor.rb

Tell why build aborted

---

ruby/lib/ci/queue/redis/base.rb
ruby/lib/ci/queue/redis/supervisor.rb

Print remaining tests

---

ruby/lib/minitest/queue/build_status_reporter.rb
ruby/lib/minitest/queue/runner.rb

[Reapply "Dump JSON directly to file instead of buffering"](https://github.com/Shopify/ci-queue/commit/c4eaa5212e81d311ceee50011fcddb574a9c457e)
This reverts commit https://github.com/Shopify/ci-queue/commit/30e16eed40773b9f81074cb08fab3dfa8f322316.
---
[Use block so Files are closed after writing](https://github.com/Shopify/ci-queue/commit/80050a346e1f570868d26fa204ff485afb67900f)
This fixes test errors where the file had no content.

Reapply "Dump JSON directly to file instead of buffering"

---

ruby/lib/ci/queue/configuration.rb
ruby/test/ci/queue/configuration_test.rb

This makes it simpler for our ci-queue client to specify the list of disabled tests.

Specify flaky tests in junit.xml format

---

ruby/lib/ci/queue/redis/worker.rb

`setnx` which we use during leader election is currently not safe to retry via Redis reconnect_attempts as the command could succeed on server side but we run into a client timeout. In this case, any subsequent `setnx` calls will return false and leader election will fail.
Instead we're now setting a uniq value for setup and compare it when we fail.

Make leader election idempotent

---

ruby/lib/ci/queue/redis/build_record.rb
ruby/lib/minitest/queue.rb
ruby/lib/minitest/queue/build_status_recorder.rb
ruby/lib/rspec/queue.rb
ruby/test/integration/minitest_redis_test.rb
ruby/test/minitest/queue/build_status_recorder_test.rb

Because the `ack` and the error registration are so far apart, it's possible that the reporter exit successfully even though one test failed.
The worker first ack that the test was ran, then report the error on stdout and other places, then finally record the error in redis.
This leave a relatively big window during which the reporter might see that the queue is empty, but no errors is reported yet.
To fix that we must ack and report the error atomically, which require to move the ack inside the error reporter.
This commit doesn't fully close the race condition but make it much smaller, and make it much easier to bundle the ack and error registration in a single atomic lua script.

Refactor test ACK to reduce the race condition window

---

ruby/lib/ci/queue/redis.rb
ruby/lib/ci/queue/redis/build_record.rb
ruby/lib/ci/queue/redis/grind_record.rb
ruby/lib/ci/queue/redis/test_time_record.rb

This bug has been fixed in the redis gem > 5 so we can remove this workaround.
https://github.com/Shopify/ci-queue/issues/84

Remove binary conversion

---

redis/acknowledge.lua
ruby/lib/ci/queue/redis/base.rb
ruby/lib/ci/queue/redis/build_record.rb
ruby/lib/ci/queue/redis/worker.rb
ruby/lib/ci/queue/static.rb

There is a small race condition between acknowledge and recording the error in which the reporter may see the queue empty and no error recorded and wrongly thinks it's a success.
Follow up from https://github.com/Shopify/ci-queue/pull/323

Fix race condition

---

ruby/lib/minitest/queue.rb

Extracted from https://github.com/Shopify/ci-queue/pull/334
This is purely an internal refactor, to make it easier to do some things in parallel where we need parts of the patch that are not currently exposed.

Move `Minitest.__run` patch internals to `Minitest::Queue.run`

---

ruby/lib/ci/queue/redis/worker.rb
ruby/lib/ci/queue/static.rb
ruby/test/minitest/queue/build_status_recorder_test.rb

Currently, ci-queue only allows one test to be reserved at a time. We are attempting to implement test parallelism within ci-queue jobs, which requires that the server process reserves more than this.
I've made some changes here to support that change:
- Implement `reserved_test` as a set instead of a single test (renamed to `reserved_tests`)
- Only raise on `acknowledge` and `requeue`, not on `reserve` since there is nothing to check when reserving a test.
I've implemented this for everything, i.e. without some configuration to switch it on and off. This simplifies things a lot, because I don't think ensuring that we're not reserving when a test has already been reserved is actually doing much atm. But maybe I'm missing something.

Remove rate limit on reserved tests

---

ruby/lib/minitest/queue/order_reporter.rb
ruby/test/integration/grind_redis_test.rb
ruby/test/integration/minitest_redis_test.rb
ruby/test/minitest/queue/order_reporter_test.rb
ruby/test/test_helper.rb

Make `Minitest::Queue::OrderReporter` parallel-friendly. This is essentially done by appending and truncating to the log file instead of writing to it. The object also doesn't depend on the start hook anymore to initialize the log file, because that isn't called in forked workers.

Make the CI Queue reporters work in parallel
