Shopify/ci-queue

dev.yml, test/ci/queue/redis_supervisor_test.rb, test/ci/queue/redis_test.rb, test/integration/redis_test.rb, test/minitest/reporters/redis_reporter_test.rb
@Shopify/pipeline for review please
=> Add `dev` support, with redis under railgun

lib/ci/queue/redis/worker.rb, lib/ci/queue/static.rb, lib/minitest/queue.rb, lib/minitest/reporters/redis_reporter.rb, test/ci/queue/redis_test.rb, test/support/queue_helpers.rb, test/support/shared_queue_assertions.rb
Ref: https://github.com/Shopify/ci-queue/issues/12
=> Prevent requeuing of timed out tests

ruby/lib/ci/queue/redis/base.rb, ruby/test/ci/queue/redis_test.rb, ruby/test/fixtures/redis-runner.rb
This makes the test suite pass for me with fewer warnings.
=> Minor fixes

python/ciqueue/distributed.py
@prabcs this adds a try catch to the iterator to make it match up with the ruby implementation.
=> add try catch

python/setup.py
As suggested by https://github.com/Shopify/ci-queue/pull/34#issuecomment-344943270
=> Fix Python test suite

ruby/lib/ci/queue/configuration.rb, ruby/lib/minitest/queue/runner.rb, ruby/test/ci/queue/configuration_test.rb
This should makes setup much easier for most people.
=> Auto-detect part of the configuration when executed on known CI providers

README.md, ruby/README.md, ruby/lib/ci/queue/configuration.rb, ruby/lib/minitest/queue/runner.rb, ruby/test/integration/redis_test.rb
Pretty much all is in the title. The documentation might still be a little light but it's better than nothing I guess...
I think after this PR we can cut a new release.
=> Document minitest-queue usage

ruby/README.md, ruby/ci-queue.gemspec, ruby/exe/rspec-queue, ruby/lib/minitest/queue/runner.rb, ruby/lib/rspec/queue.rb, ruby/test/fixtures/.rspec, ruby/test/fixtures/spec/dummy_spec.rb, ruby/test/fixtures/spec/spec_helper.rb, ruby/test/integration/rspec_redis_test.rb, ruby/test/support/output_test_helpers.rb, ruby/test/test_helper.rb
As stated in the README, this is missing centralized reporting as well as requeueing. But those 2 are somewhat optional, and tricky to implement, so I'd rather work on them in followup PRs.
I don't except a throughout review, since most of the code is patching RSpec internals and that would take a while to grasp. But a quick sanity check is more than welcome.
=> Initial RSpec integration

python/ciqueue/_pytest/outcomes.py, python/ciqueue/pytest.py, python/tests/test_pytest.py
fixes https://github.com/Shopify/ci-queue/issues/48
=> roll back junit trackers on skip, and add tests

python/ciqueue/_pytest/outcomes.py, python/ciqueue/pytest.py, python/setup.py, python/tests/test_pytest.py
This PR enables ciqueue to work with versions of pytest up until the latest (3.3.1)
=> support up to pytest 3.3.1

ruby/.gitignore, ruby/lib/minitest/queue.rb, ruby/lib/minitest/queue/junit_reporter.rb, ruby/lib/minitest/queue/runner.rb, ruby/test/integration/minitest_redis_test.rb, ruby/test/support/output_test_helpers.rb
This reporter is mostly taken from `minitest-reporters` but heavily simplified.
In a followup I'd like to extend it to include informations such as requeue etc.
=> Embed a JUnit reporter for minitest

python/Makefile
=> Fix python build

ruby/Gemfile, ruby/lib/ci/queue/redis/build_record.rb, ruby/test/fixtures/test/test_helper.rb, ruby/test/fixtures/test/utf8_test.rb, ruby/test/integration/minitest_redis_test.rb
Fix: https://github.com/Shopify/ci-queue/issues/84#issuecomment-402667045
@mrsimo this should fix your issue. Can you try this branch on your test suite?
=> Coerce test id and error payload to binary encoding

ruby/lib/ci/queue/version.rb
Bump release for https://github.com/Shopify/ci-queue/pull/96
I can't see a changelog anywhere, so I'll add it as a comment when I tag
=> Release 0.15.1

ruby/test/minitest/queue/build_status_recorder_test.rb
The file did not have a `_test.rb` suffix, so it wasn't running. I added the suffix, and fixed the test failures.
=> Fix build_status_record_test.rb

ruby/ci-queue.gemspec, ruby/lib/minitest/queue.rb, ruby/lib/minitest/queue/failure_formatter.rb, ruby/test/minitest/queue/test_time_recorder_test.rb, ruby/test/minitest/queue/test_time_reporter_test.rb, ruby/test/support/reporter_test_helper.rb
=> Revert "Clean up some old backwards compatibility code that we can get rid off"

ruby/lib/ci/queue/version.rb
I've updated the output file for the failure file in #148 
So we can probably bump the version.
=> bump version

ruby/lib/ci/queue/version.rb
Release 0.23.2
* https://github.com/Shopify/ci-queue/pull/189
* https://github.com/Shopify/ci-queue/pull/188
=> Release 0.24.0

.github/workflows/tests.yml
Add Ruby 3.2, remove Ruby 2.6 in CI
=> 🎅 Add Ruby 3.2, remove Ruby 2.6 in CI

ruby/lib/ci/queue/build_record.rb
Introduced in https://github.com/Shopify/ci-queue/commit/77d83d1b103543426eece40fc8ae22c1852c5b07
=> Fix method signature

ruby/lib/ci/queue/redis.rb, ruby/lib/ci/queue/redis/base.rb
Reported by @pedropb, superseding https://github.com/Shopify/ci-queue/pull/246.
Related to https://github.com/Shopify/ci-queue/pull/244
=> Don't require Redis > 5

ruby/lib/minitest/queue.rb
Gracefully handle heartbeat monitor dies
=> Gracefully handle heartbeat monitor dies

ruby/lib/ci/queue/static.rb, ruby/test/ci/queue/static_test.rb
=> Fix expiry of static queue

ruby/lib/ci/queue/redis/supervisor.rb
If you set `--timeout 600` and `--queue-init-timeout 300` you actually wait 900 seconds. IMO if you specify `--timeout` it should be the total timeout, including the init time.
=> Consider waiting for master in total duration

ruby/Gemfile.lock
=> Bump version in Gemfile.lock

ruby/lib/minitest/queue/junit_reporter.rb, ruby/test/integration/minitest_redis_test.rb, ruby/test/support/output_test_helpers.rb
Add timestamp to junit.xml export.
=> Add timestamp to junit.xml export

ruby/lib/ci/queue/redis/build_record.rb
=> Remove dead code

ruby/lib/ci/queue/redis/build_record.rb, ruby/test/minitest/queue/build_status_recorder_test.rb, ruby/test/minitest/queue/build_status_reporter_test.rb
We should only increment this counter when we acknowledge the test.
=> Fix increment_test_failed

ruby/lib/minitest/queue/junit_reporter.rb
Make it possible to set JUnitXML export path
=> Make it possible to set JUnitXML export path

ruby/lib/ci/queue/configuration.rb
=> Configure retries via env

ruby/lib/ci/queue/redis/worker.rb
=> Don't reserve `nil` when there are no tests left
